name: Update character.json

on:
  push:
    branches:
      - main
    paths:
      - "./character.json"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

env:
  PROJECT_ID: ${{ vars.PROJECT_ID || secrets.PROJECT_ID }}
  PHALA_CLOUD_API_KEY: ${{ vars.PHALA_CLOUD_API_KEY || secrets.PHALA_CLOUD_API_KEY }}
  ENCRYPTED_ENV: ${{ vars.ENCRYPTED_ENV || secrets.ENCRYPTED_ENV }}
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: update json
        run: |
          export CHARACTER=$(cat ./character.json | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
          export DATA=$(echo '{"characterfile": "'${CHARACTER}'", "env_keys": ["TELEGRAM_BOT_TOKEN", "REDPILL_API_KEY", "REDPILL_MODEL", "CHARACTER_DATA"], "encrypted_env": "'${{ env.ENCRYPTED_ENV }}'", "image": "phalanetwork/eliza:v0.1.8-alpha.1"}')
          curl -X PUT -H "X-API-Key: ${{ env.PHALA_CLOUD_API_KEY }}" -H 'Content-Type: application/json' -d "${DATA}" https://cloud-api.phala.network/api/v1/projects/${{ env.PROJECT_ID }}/eliza
